# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 06:45
from __future__ import unicode_literals

import django.conf
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(django.settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mlh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=28)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
