# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlh', '0003_auto_20171029_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
